### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by robhudson** [mozilla/shielddash#41]
On Firefox dev tools I am unable to use the site because of an error in the console, "SecurityError: The operation is insecure." after log in.

**Comment by openjck** [comment]
This happened on Heroku for Rob

**Comment by openjck** [comment]
I had a feeling this might be related to a privacy add-on, and it looks that may be the case:

> &lt;robhudson&gt; tested on another laptop and it works so it must be somethign with my plugins or profile
